# coding: utf-8

"""
    Ring-Moon Systems OpenAPI

    This is a simple API wrapping the OPUS API of the PDS Ring-Moon Systems node.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kmichael.aye@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metadata_v2_opus_id_json_get(self):
        """Test case for metadata_v2_opus_id_json_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
