# coding: utf-8

"""
    Ring-Moon Systems OpenAPI

    This is a simple API wrapping the OPUS API of the PDS Ring-Moon Systems node.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kmichael.aye@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Ring-Moon Systems OpenAPI",
    author_email="kmichael.aye@gmail.com",
    url="",
    keywords=["Swagger", "Ring-Moon Systems OpenAPI"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is a simple API wrapping the OPUS API of the PDS Ring-Moon Systems node.  # noqa: E501
    """
)
